INSERT INTO author (author_name, author_id) VALUES
('A. Bartlett Giamatti', 1),
('A. Elizabeth Delany', 2),
('A. Merritt', 3),
('A. Roger Merrill', 4),
('A. Walton Litz', 5),
('A.B. Yehoshua', 6),
('A.D.P. Briggs', 7),
('A.E. Cunningham', 8),
('A.E. van Vogt', 9),
('A.G. Pasquella', 10),
('A.H. Armstrong', 11),
('A.J. Arberry', 12),
('A.J. Ayer', 13),
('A.J. Jacobs', 14),
('A.J. McAllister', 15),
('A.M. Dellamonica', 16),
('A.M. Homes', 17),
('A.N. Roquelaure', 18),
('A.N. Wilson', 19),
('A.R. Braunmuller', 20),
('A.R. Taylor', 21),
('A.S. Byatt', 22),
('A.T. Hatto', 23),
('A.V. Miller', 24),
('Aaron Anderson', 25),
('Aaron Asher', 26),
('Aaron Medwin', 27),
('Aaron Rosenberg', 28),
('Aaron Shepard', 29);