INSERT INTO publisher (publisher_name, publisher_id) VALUES
('10/18', 1),
('1st Book Library', 2),
('1st World Library', 3),
('A & C Black (Childrens books)', 4),
('A Harvest Book/Harcourt Inc.', 5),
('A K PETERS', 6),
('AA World Services', 7),
('Abacus', 8),
('Abacus Books', 9),
('Abacus Books (London)', 10),
('Abdo Publishing Company', 11),
('Abingdon Press', 12),
('Abradale Books/Harry N. Abrams', 13),
('Abraham Guillen Press', 14),
('Abrams', 15),
('Absolute Press', 16),
('Abstract Studio', 17),
('Academic Press', 18),
('Academica Press', 19),
('Academy Chicago Publishers', 20),
('Ace', 21),
('Ace Book', 22),
('Ace Books', 23),
('Ace Hardcover', 24),
('Ace Trade', 25),
('Ace/SFBC', 26),
('Acento Editorial', 27),
('Acropolis Books (NY)', 28),
('Actes Sud', 29);